// Picture for products without a photo: an illustration of the product type, chosen from the name.
// Illustrations: Microsoft Fluent Emoji (MIT licence), stored in public/art.

const R = (pattern: string, art: string) => [new RegExp(pattern, 'i'), art] as const;

// Checked top to bottom against the product name, only in the groups that fit the product's category.
const GROUPS = {
  care: [
    R(String.raw`bottle brush|nipple brush`, 'sponge'),
    R(String.raw`diaper|diper|dipaper|\bpants?\b.*\b(nb|xs|s|m|l|xl|xxl|xxxl)\s*\d|wonder.?pants|mamy ?poko|pampers|huggies|chikool`, 'briefs'),
    R(String.raw`feeding bottle|feeder|baby bottle|nipple|sipper|teether|pacifier`, 'baby_bottle'),
    R(String.raw`lactogen|cerelac|formula|farex|nan pro|similac|lactodex|ceregrow`, 'baby_bottle'),
    R(String.raw`sanitary|\bpads?\b|napkin|panty ?liner|period pant|whisper|stayfree|sofy|tampon`, 'hibiscus'),
    R(String.raw`wipes?\b|tissue|toilet (roll|paper)|kitchen (roll|towel)|napkin paper`, 'roll_of_paper'),
    R(String.raw`cotton (bud|swab|ball)|\bbuds\b`, 'adhesive_bandage'),
    R(String.raw`bandage|band[- ]?aid|plaster|antiseptic|dettol liquid|savlon`, 'adhesive_bandage'),
    R(String.raw`vicks|balm\b|pain relief|moov|zandu|iodex|strepsils|hajmola|eno\b|tablet|capsule|syrup.*(cough|cold)|chyawan|shilajit|vitamin (tablet|capsule)`, 'pill'),
    R(String.raw`thermometer`, 'thermometer'),
    R(String.raw`condom|pregnancy`, 'package'),
    R(String.raw`tooth ?brush|toothbrush|tooth brush`, 'toothbrush'),
    R(String.raw`tooth ?paste|toothpest|tothpaste|colgate|pepsodent|close ?up|sensodyne|dant|manjan|mouth ?wash|listerine`, 'toothbrush'),
    R(String.raw`razor|shav(e|ing)|blade|gillette|gillete|trimmer`, 'razor'),
    R(String.raw`lipstick|lipstic|lip ?(gloss|liner|tint|balm|blam|oil|care|colou?r|stick)|\blips?\b`, 'lipstick'),
    R(String.raw`nail ?(polish|police|paint|colou?r|lacquer|remover|art)`, 'nail_polish'),
    R(String.raw`nail ?(cutter|clipper|file)|manicure|pedicure|tweezer`, 'scissors'),
    R(String.raw`kajal|eyeliner|mascara|eye ?(shadow|brow|lash)|foundation|primer|concealer|compact|blush|highlighter(?!.*(pen|marker))|makeup|make-up|powder puff|beauty blender|setting spray|sindoor|bindi`, 'lipstick'),
    R(String.raw`perfume|parfum|perfum|deo\b|deodorant|body ?(spray|mist)|fogg|scent|attar|roll[- ]?on|eau de|cologne|bellavita|envy\b|\bplom\b|body lovin`, 'sparkles'),
    R(String.raw`\bsoap\b|bathing bar|beauty bar|hand ?wash|handwash|body ?wash|shower gel|lifebuoy|santoor|\blux\b|dove bar|medimix|pears`, 'soap'),
    R(String.raw`shampoo|conditioner|hair (oil|serum|mask|spa|colou?r|dye|gel|wax|cream)|coconut oil|parachute|navaratna|kesh|keratin|henna|mehendi`, 'lotion_bottle'),
    R(String.raw`comb\b|hair ?brush`, 'hair_pick'),
    R(String.raw`face ?wash|facewash|cleanser|serum|toner|sun ?screen|sunscreen|spf|moisturi|cream|lotion|gel\b|scrub|face (pack|mask)|sheet mask|rose ?water|gulab|vaseline|petroleum jelly|talc|powder\b.*(baby|prickly|dusting|body)|body (oil|butter)|glycerin`, 'lotion_bottle'),
    R(String.raw`mirror|mirro\b|mirron`, 'mirror'),
    R(String.raw`detergent|surf\b|washing powder|ariel|tide\b|\brin\b|wheel\b|henko|ghadi|laundry|fabric|comfort (fabric|mor|after)|matic|vanish|robin blue|bleach`, 'bubbles'),
    R(String.raw`dish ?wash|vim\b|pril|exo\b|scrubber|scourer|sponge|steel wool`, 'sponge'),
    R(String.raw`harpic|toilet|phenyl|lizol|colin|floor clean|glass clean|domex|sanifresh|mr\.? ?muscle|kitchen cleaner|disinfectant|drain`, 'bucket'),
    R(String.raw`\bmop\b|broom|jharu|duster|dust ?pan|wiper|cleaning (cloth|brush)|pochha`, 'broom'),
    R(String.raw`mosquito|good ?night|all ?out|mortein|\bhit\b|baygon|odomos|cockroach|repellent|\bcoil\b|insect|rat (kill|cake)`, 'mosquito'),
    R(String.raw`air ?fresh|odonil|aer\b|aermatic|room (spray|fresh)|naphthalene|ambi ?pur|glade`, 'tulip'),
    R(String.raw`garbage bag|dustbin bag|trash bag|foil\b|cling`, 'package'),
  ],
  drinks: [
    R(String.raw`beer|bier|pilsner|lager|tuborg|carlsberg|barahsinghe|barasinghe|arna\b|gorkha (strong|premium)|nepal ice|malt beverage|cider`, 'beer_mug'),
    R(String.raw`wine|winery|chenet|sweet red|port\b`, 'wine_glass'),
    R(String.raw`whisk(e)?y|vodka|voodka|\brum\b|\bgin\b|brandy|tequila|old durbar|black label|red label|black oak|signature|8848|golden oak|glenlivet|vat 69|highlander|singleton|absolute?|reserve`, 'tumbler_glass'),
    R(String.raw`cigarette|cigar|hookah|hooka|hukka|molasses|shisha|rolling paper|charcoal|surya|shikhar|khukuri cig`, 'cigarette'),
    R(String.raw`coffee|nescafe|\bbru\b|cappuccino|latte|espresso|maccoffee|cafe`, 'hot_beverage'),
    R(String.raw`\btea\b|chiya|green tea|tokla|tokala|dilmah|lipton|sai kripa|taza|masala tea`, 'teacup_without_handle'),
    R(String.raw`energy drink|red ?bull|sting\b|monster|xl energy|x cite|tiger energy`, 'cup_with_straw'),
    R(String.raw`horlicks|bournvita|bourn vita|complan|boost\b|milo\b|glucon|glucose|glucovita|ensure\b|protinex|sattu|satu\b|rasna|tang\b`, 'glass_of_milk'),
    R(String.raw`juice|frooti|frooto|maaza|slice\b|real\b|tropicana|appy|squash|crush\b|sharbat|drink|nata|smooah|lassi|nimbu pani`, 'beverage_box'),
    R(String.raw`\bcoke\b|coca|pepsi|sprite|fanta|dew\b|7 ?up|mirinda|thums up|campa|soda\b|cola|soft drink|mojito|tonic`, 'cup_with_straw'),
    R(String.raw`mineral water|drinking water|kinley|aquafina|bisleri|\bwater\b.*\d+ ?(ml|l|ltr)`, 'potable_water'),
  ],
  food: [
    R(String.raw`noodle|buldak|samyang|nodles|noddles|ramen|ramyun|maggi\b|wai[- ]?wai|rara\b|mayos|preeti|chowmein|chow mein|chau ?chau|thukpa|soup`, 'steaming_bowl'),
    R(String.raw`ice ?cream|ice crem|kulfi|cornetto|chocobar|falala|cone\b`, 'soft_ice_cream'),
    R(String.raw`chocolate|choco|dairy milk|cadbury|kit ?kat|snickers|munch|perk\b|5 ?star|ferrero|raffaello|kinder|hershey|toblerone|galaxy|milky ?bar|bar ?one|truffle|nutella|m&ms`, 'chocolate_bar'),
    R(String.raw`lollipop|lolipop|lolly|chupa`, 'lollipop'),
    R(String.raw`candy|candies|toffee|eclair|gems\b|mentos|alpenliebe|jelly|gummy|marshmallow|chewing|chew ?gum|bubble ?gum|center ?fresh|pulse\b|polo\b|mint\b|mouth fresh|supari|pan masala|paan`, 'candy'),
    R(String.raw`biscuit|biscut|biskut|cookie|cookes|cokies|cracker|marie|parle|britannia|good ?day|oreo|bourbon|digestive|wafer|rusk|toast\b|krackjack|monaco|hide ?& ?seek|jim ?jam|bisk|khari`, 'cookie'),
    R(String.raw`popcorn`, 'popcorn'),
    R(String.raw`chips|crisps|lays\b|kurkure|cheetos|doritos|pringles|bingo|nachos|puff|stix|sticks?\b|kurmure|khaja|chiura|pani ?puri|papad|prawn cracker|balls?`, 'pretzel'),
    R(String.raw`namkeen|namkin|namking|bhujia|bhujiya|dalmoth|dalmot|dalmonth|dhalmooth|mixture|furandana|lakhamari|sadabahar`, 'pretzel'),
    R(String.raw`peanut butter`, 'jar'),
    R(String.raw`peanut|groundnut`, 'peanuts'),
    R(String.raw`cake|muffin|brownie|swiss roll|pastry|pie\b|donut|doughnut|cupcake`, 'shortcake'),
    R(String.raw`bread|bun\b|pav\b|croissant|parotha|paratha|lachha`, 'bread'),
    R(String.raw`sweets?\b|laddu|ladoo|barfi|rasgulla|gulab jamun|soan ?papdi|peda\b|halwa|mithai|gudpak`, 'shortcake'),
    R(String.raw`momo|dumpling`, 'dumpling'),
    R(String.raw`^(?!.*(masala|seasoning|essence|khurak|powder)).*(sausage|sauasge|saussage|salami|nugget|chicken|mutton|meat\b|ham\b|bacon|wings|luncheon|sukuti|jerky)`, 'poultry_leg'),
    R(String.raw`^(?!.*(masala|chop|chhop|pickle)).*(\bfish|prawn|shrimp|tuna|sardine|mackerel)`, 'fish'),
    R(String.raw`\beggs?\b`, 'egg'),
    R(String.raw`paneer|cheese|chhurpi|churpi`, 'cheese_wedge'),
    R(String.raw`butter\b|ghee`, 'butter'),
    R(String.raw`milk|curd|yogh?urt|dahi|dairy|creamer|whitener|condensed`, 'glass_of_milk'),
    R(String.raw`pasta|macaroni|spaghetti|vermicelli|sevai|seviyan|penne`, 'spaghetti'),
    R(String.raw`corn ?flakes|cereal|muesli|granola|chocos|oats\b|oat\b|daliya|dalia`, 'bowl_with_spoon'),
    R(String.raw`\brice\b|basmati|chamal|jeera masino|mansuli|pokhareli|jasmine|sella|beaten rice|poha`, 'cooked_rice'),
    R(String.raw`atta|aata|flour|maida|sooji|suji|rawa|besan|beshan|pitho|semolina|makai|makkai|millet|kodo|fapar|barley|sabudana|sabudh?ana|quinoa|wheat`, 'sheaf_of_rice'),
    R(String.raw`\bdal\b|daal|lentil|masoor|moong|mung|chana|rajma|beans?\b|toor|arhar|urad|\bmas\b|gahat|bodi|kerau|peas\b|bhatmas|soya|simi|bhatta|chickpea`, 'beans'),
    R(String.raw`\boil\b|oli\b|sunflower|mustard oil|olive oil|dalda|vanaspati|fortune|dhara|saffola`, 'pouring_liquid'),
    R(String.raw`honey`, 'honey_pot'),
    R(String.raw`sauce|sause|ketchup|mayo|vinegar|soy\b`, 'jar'),
    R(String.raw`pickle|achar|achaar|chutney|chhop|chope?\b|jam\b|jams\b|marmalade|spread|paste\b(?!.*tooth)`, 'jar'),
    R(String.raw`salt|nun\b|namak`, 'salt'),
    R(String.raw`sugar|chini|jaggery|gud\b|chaku|mishri|misri`, 'salt'),
    R(String.raw`chilli|chili|chilly|khursani|pepper|paprika|mirch`, 'hot_pepper'),
    R(String.raw`garlic|lasun`, 'garlic'),
    R(String.raw`ginger|turmeric|haldi|masala|mashala|spice|jeera|cumin|dhaniya|dhania|coriander|garam|methi|jwano|ajwain|laung|clove|sukmel|cardamom|elaichi|dalchini|cinnamon|timur|timmur|hing|saffron|kesar|tejpat|tej patta|sauf|saunf|fennel|oregano|rosemary|seasoning|curry|tadka|kitchen king|jimmu|jimbu|teel|til\b|sesame|seeds?\b|panch ?for`, 'jar'),
    R(String.raw`cashew|kaju|almond|badam|pista|walnut|wallnut|raisin|kishmis|dates\b|khajur|anjir|fig\b|apricot|khurbani|makhana|nuts?\b|dry ?fruit|chestnut`, 'chestnut'),
    R(String.raw`coconut`, 'coconut'),
    R(String.raw`olives?`, 'olive'),
    R(String.raw`mushroom|corn\b|canned|tin\b|baked beans|kernel`, 'canned_food'),
    R(String.raw`apple`, 'red_apple'),
    R(String.raw`banana`, 'banana'),
    R(String.raw`mango`, 'mango'),
    R(String.raw`lemon|lime`, 'lemon'),
    R(String.raw`tomato`, 'tomato'),
    R(String.raw`onion`, 'onion'),
    R(String.raw`potato`, 'roasted_sweet_potato'),
  ],
  home: [
    R(String.raw`pressure cooker|cooker|kadai|kadhai|karahi|fry ?pan|\bpan\b|tawa|patila|handi|casserole|\bpot\b|wok|cookware|steamer|dekchi`, 'cooking'),
    R(String.raw`knife|knives|peeler|grater|chopper|slicer|cutting board|chopping board`, 'kitchen_knife'),
    R(String.raw`spoon|ladle|spatula|fork\b|tong\b|whisk\b|strainer|sieve|colander|masher|rolling pin|belna|chakla|skewer`, 'spoon'),
    R(String.raw`chopstick`, 'chopsticks'),
    R(String.raw`lunch ?box|tiffin|hot ?case|food container|container|airtight`, 'bento_box'),
    R(String.raw`bottle|flask|thermos|thormas|thermas|vacuum|sipper|water jug`, 'cup_with_straw'),
    R(String.raw`\bmug\b|\bmugs\b|\bcup\b|\bcups\b|tea ?pot|kettle(?!.*electric)|saucer`, 'teapot'),
    R(String.raw`glass|tumbler|jug\b|pitcher|glassware|decanter`, 'tumbler_glass'),
    R(String.raw`plate|bowl|thali|tray|dinner|cutlery|crockery|melamine|serving|table ?(mat|cloth)|placemat|coaster`, 'fork_and_knife_with_plate'),
    R(String.raw`\bjar\b|spice (box|rack)|masala (box|dani|dabba)|dibba`, 'jar'),
    R(String.raw`lighter|match ?box|salai`, 'fire'),
    R(String.raw`bucket|\btub\b|bath ?mug|dustbin|\bbin\b`, 'bucket'),
    R(String.raw`basket|storage|organi[sz]er|rack\b|shelf|drawer|box\b|cabinet`, 'basket'),
    R(String.raw`hanger|hook|clip.*cloth|cloth.*(clip|peg|rope|line)|pegs?\b`, 'hook'),
    R(String.raw`chair|stool|table\b`, 'chair'),
    R(String.raw`frame|decor|show ?piece|show plece|vase|artificial|clock|curtain|cushion|pillow|carpet|mat\b|towel|bed ?sheet|blanket`, 'framed_picture'),
    R(String.raw`candle|diyo|diya|batti|dipawali|dipawoli`, 'diya_lamp'),
    R(String.raw`umbrella|umberlla|raincoat`, 'umbrella'),
    R(String.raw`luggage|trolley|suitcase|travel`, 'luggage'),
    R(String.raw`lock\b|padlock|pad lock|locket(?! )`, 'locked'),
    R(String.raw`key ?(ring|chain)|keyring|keychain`, 'key'),
    R(String.raw`hammer|screw|plier|spanner|wrench|drill|tool`, 'wrench'),
    R(String.raw`needle|thread|sewing|button`, 'thread'),
    R(String.raw`safety pin`, 'safety_pin'),
    R(String.raw`shoe (polish|brush|shine)|cherry blossom|kiwi\b`, 'running_shoe'),
    R(String.raw`\bcar\b(?!.*(toy|remote|r/c|metal|racing|no\.))|bike\b(?!.*(toy|racing|moto))|helmet|engine oil`, 'automobile'),
  ],
  electronics: [
    R(String.raw`battery|batteries|bettery|duracell|eveready|\bcell\b`, 'battery'),
    R(String.raw`torch|tourch|flash ?light|emergency light`, 'flashlight'),
    R(String.raw`bulb|\bled\b|light\b|lamp`, 'light_bulb'),
    R(String.raw`headphone|earphone|earbud|neckband|speaker|bluetooth`, 'headphone'),
    R(String.raw`charger|mobile|usb|cable|power ?bank|phone`, 'mobile_phone'),
    R(String.raw`kettle|mixer|grinder|blender|juicer|toaster|rice cooker|induction|iron\b|dryer|heater|fan\b|chapati maker|pump|electric|extension|plug|socket|switch|wire\b|door bell`, 'electric_plug'),
  ],
  stationery: [
    R(String.raw`note ?book|notebook|copy\b|register|diary|dairy (no|\d|sc)|sketch ?book|drawing book|journal|note\d|notes? book`, 'notebook'),
    R(String.raw`pencil|pensil|eraser|earse|sharpener|lead\b`, 'pencil'),
    R(String.raw`\bpens?\b|ball ?pen|gel pen|marker|highlighter|highiter|higlighter|highighter|refill|\bink\b`, 'pen'),
    R(String.raw`colou?r(ing)? ?(pencil|pen|book|set|box)|crayon|paint|acrylic|water ?colou?r|pastel|glitter|art set|craft|clay|stencil|canvas`, 'artist_palette'),
    R(String.raw`scale|ruler|geometry|compass|protractor`, 'straight_ruler'),
    R(String.raw`scissor|cutter`, 'scissors'),
    R(String.raw`stapler|staple|clip\b|pin\b|pins\b|punch|tape\b|glue|fevi|gum\b|sticker|label`, 'paperclip'),
    R(String.raw`school bag|backpack|pencil (box|case|pouch)`, 'backpack'),
    R(String.raw`\bbook\b|\bbooks\b|paper|a4\b|chart|envelope|file\b|folder|sticky|stick notes|memo|writing pad|slate`, 'memo'),
  ],
  toys: [
    R(String.raw`teddy|soft toy|plush`, 'teddy_bear'),
    R(String.raw`doll|barbi|barbie|baby girl|pretty girl`, 'nesting_dolls'),
    R(String.raw`r/c|remote control|\bcar\b|truck|jeep|racing|dozer|dojer|bike|train\b|vehicle|stunt`, 'racing_car'),
    R(String.raw`plane|aircraft|helicopter|airliner|drone`, 'kite'),
    R(String.raw`robot|transformer`, 'robot'),
    R(String.raw`dinos(a|u)r|t-?rex|animal`, 't-rex'),
    R(String.raw`gun\b|pistol|shooting|water gun`, 'water_pistol'),
    R(String.raw`puzzle|blocks?\b|lego|building|cube|tetris|learning|educational|shape`, 'puzzle_piece'),
    R(String.raw`ludo|chess|carrom|uno\b|cards?\b|playing|game|dice|tas\b`, 'game_die'),
    R(String.raw`football|soccer`, 'soccer_ball'),
    R(String.raw`basketball|volleyball|\bball\b|pu ?ball`, 'basketball'),
    R(String.raw`badminton|shuttle|racket|racquet`, 'badminton'),
    R(String.raw`cricket|\bbat\b`, 'cricket_game'),
    R(String.raw`skipping|yoga|dumbbell|gym|fitness|swim|float|pool|intex|bestway`, 'flying_disc'),
    R(String.raw`kite`, 'kite'),
    R(String.raw`piano|paino|guitar|drum|music|musical|trumpet|whistle`, 'party_popper'),
    R(String.raw`slime|dough|squish|bubble\b|spinner|fidget|pop it|yo-?yo`, 'yo-yo'),
  ],
  fashion: [
    R(String.raw`earring|earing|jhumka|necklace|pendant|locket|chain\b|bracelet|bangle|anklet|payal|nose ?pin|mangal|tilhari|jewel|jwel|jewellry|choker|chokar|brooch|jagler`, 'ring'),
    R(String.raw`\bring\b|\brings\b`, 'ring'),
    R(String.raw`moti|mala\b|beads?|rudraksh|rudrax|kanthi|pote\b`, 'prayer_beads'),
    R(String.raw`crown|tiara`, 'crown'),
    R(String.raw`hair ?(band|clip|pin|tie|rubber|accessor|claw|bow|catcher|clutcher)|clip|bow\b|scrunch|rubber|kata\b|pitpite|juda|chimti|headband`, 'ribbon'),
    R(String.raw`sunglass|goggle|guggle|gugles|specs\b`, 'sunglasses'),
    R(String.raw`watch\b`, 'watch'),
    R(String.raw`hand ?bag|purse|wallet|clutch|sling bag|pouch`, 'handbag'),
    R(String.raw`\bbag\b|\bbags\b`, 'shopping_bags'),
    R(String.raw`shoe|slipper|sandal|chappal|flip ?flop|boot|sneaker`, 'running_shoe'),
    R(String.raw`socks?\b`, 'socks'),
    R(String.raw`cap\b|hat\b`, 'billed_cap'),
    R(String.raw`gloves?|warm\b`, 'gloves'),
    R(String.raw`scarf|shawl|stole\b|muffler|dupatta`, 'scarf'),
    R(String.raw`dress|frock|gown|kurti|kurta|saree|lehenga|skirt|top\b|tops\b`, 'dress'),
    R(String.raw`t[- ]?shirt|shirt|pant\b|trouser|jeans|shorts|jacket|sweater|hoodie|vest|kapada|b\.b top|inner`, 't-shirt'),
  ],
  gifts: [
    R(String.raw`agarbatti|incense|dhoop|dhup|kapur|camphor|puja|pooja|abir|tika\b|janai|dhago|chandan|mangal ?deep|zed black|rakhi|rakhshya|raksha`, 'diya_lamp'),
    R(String.raw`balloo?n|ballons`, 'balloon'),
    R(String.raw`birthday|party|popper|confetti|banner|topper|number candle|celebration`, 'party_popper'),
    R(String.raw`gift`, 'wrapped_gift'),
    R(String.raw`flower|rose\b`, 'tulip'),
  ],
  pets: [
    R(String.raw`dog|puppy|pet\b|cat food|leash|collar`, 'dog_face'),
  ],
};

/** Which picture groups each category looks in, in order. */
const CATEGORY_GROUPS: Record<string, Array<keyof typeof GROUPS>> = {
  'groceries': ['food', 'drinks'],
  'snacks': ['food'],
  'beverages': ['drinks', 'food'],
  'dairy-frozen': ['food', 'drinks'],
  'liquor-smoking': ['drinks'],
  'beauty-skincare': ['care', 'fashion'],
  'health-hygiene': ['care'],
  'baby-care': ['care', 'toys', 'home'],
  'cleaning': ['care', 'home'],
  'kitchen-household': ['home', 'electronics'],
  'home-living': ['home', 'electronics', 'care'],
  'stationery': ['stationery', 'home'],
  'toys': ['toys', 'stationery'],
  'ladies-wear': ['fashion', 'care'],
  'electronics': ['electronics', 'home'],
  'gifts-puja': ['gifts', 'food', 'toys'],
  'pet-care': ['pets', 'care'],
};

/** Fallback picture per subcategory, then per category. */
const BY_SUBCATEGORY: Record<string, string> = {
  'Rice & Grains': 'cooked_rice', 'Atta, Flour & Sooji': 'sheaf_of_rice', 'Dal & Pulses': 'beans', 'Oil & Ghee': 'pouring_liquid',
  'Spices & Masala': 'jar', 'Salt, Sugar & Jaggery': 'salt', 'Noodles, Pasta & Soup': 'steaming_bowl', 'Breakfast & Cereals': 'bowl_with_spoon',
  'Dry Fruits, Nuts & Seeds': 'chestnut', 'Sauces, Pickles & Spreads': 'jar', 'Cooking Essentials': 'canned_food', 'Fruits & Vegetables': 'leafy_green',
  'Biscuits & Cookies': 'cookie', 'Chips, Namkeen & Snacks': 'pretzel', 'Chocolates & Candy': 'candy',
  'Tea & Coffee': 'hot_beverage', 'Health & Energy Drinks': 'glass_of_milk', 'Soft Drinks & Soda': 'cup_with_straw', 'Juices & Squash': 'beverage_box', Water: 'potable_water',
  'Milk, Butter & Cheese': 'glass_of_milk', 'Ice Cream & Frozen': 'ice_cream', 'Bread, Cakes & Bakery': 'bread', 'Eggs & Meat': 'egg',
  'Skin Care': 'lotion_bottle', 'Hair Care': 'lotion_bottle', 'Bath & Body': 'soap', 'Oral Care': 'toothbrush', 'Makeup & Nail Care': 'lipstick',
  'Fragrance & Deodorant': 'sparkles', "Men's Grooming": 'razor', 'Feminine Hygiene': 'hibiscus', 'Health & Wellness': 'pill',
  'Diapers & Wipes': 'briefs', 'Baby Food & Formula': 'baby_bottle', 'Baby Bath & Skin Care': 'lotion_bottle', 'Baby Accessories': 'baby_bottle',
  'Detergent & Laundry': 'bubbles', Dishwash: 'sponge', 'Floor, Toilet & Glass Cleaners': 'bucket', 'Tissues & Paper': 'roll_of_paper', 'Fresheners & Repellents': 'tulip',
  Cookware: 'cooking', 'Kitchen Tools': 'spoon', 'Cups, Mugs & Glassware': 'teapot', 'Dinnerware & Serving': 'fork_and_knife_with_plate', 'Bottles & Lunch Boxes': 'bento_box',
  'Storage & Organisers': 'basket', 'Home Decor & Furnishing': 'framed_picture', 'Bags, Umbrellas & Travel': 'umbrella', 'Tools, Hardware & Auto': 'wrench', 'Everyday Essentials': 'shopping_bags',
  'Notebooks & Paper': 'notebook', 'Pens, Pencils & Erasers': 'pencil', 'Art & Craft': 'artist_palette', 'School & Office Supplies': 'paperclip',
  Toys: 'teddy_bear', 'Games & Puzzles': 'game_die', 'Sports & Fitness': 'soccer_ball',
  Jewellery: 'ring', 'Hair Accessories': 'ribbon', 'Bags, Watches & Eyewear': 'handbag', Footwear: 'running_shoe', Clothing: 't-shirt',
  'Kitchen Appliances': 'electric_plug', 'Personal Care Appliances': 'electric_plug', 'Lights & Electricals': 'light_bulb', 'Mobile & Audio': 'headphone', 'Appliances & Gadgets': 'electric_plug',
  'Gifts & Party': 'wrapped_gift', 'Puja Items': 'diya_lamp', 'Pet Food & Accessories': 'paw_prints',
  Beer: 'beer_mug', Wine: 'wine_glass', 'Whisky, Rum & Spirits': 'tumbler_glass', 'Hookah & Smoking': 'cigarette',
};
const BY_CATEGORY: Record<string, string> = {
  groceries: 'cooked_rice', snacks: 'cookie', beverages: 'cup_with_straw', 'dairy-frozen': 'glass_of_milk', 'beauty-skincare': 'lotion_bottle',
  'health-hygiene': 'pill', 'baby-care': 'baby_bottle', cleaning: 'bubbles', 'kitchen-household': 'cooking', 'home-living': 'basket',
  stationery: 'notebook', toys: 'teddy_bear', 'ladies-wear': 'dress', electronics: 'electric_plug', 'gifts-puja': 'wrapped_gift',
  'pet-care': 'paw_prints', 'liquor-smoking': 'tumbler_glass',
};

/** Soft background colour behind the illustration, per category. */
export const ART_BACKGROUND: Record<string, string> = {
  groceries: '#eef8f1', snacks: '#fff4e5', beverages: '#eaf4ff', 'dairy-frozen': '#eef5ff', 'beauty-skincare': '#fdf0f5',
  'health-hygiene': '#fff0f2', 'baby-care': '#eef7ff', cleaning: '#e9f7f4', 'kitchen-household': '#f4f6ee', 'home-living': '#f3f0ff',
  stationery: '#fff8e6', toys: '#fff1ea', 'ladies-wear': '#fbeff8', electronics: '#fffae3', 'gifts-puja': '#fff0f6',
  'pet-care': '#f7f0e9', 'liquor-smoking': '#f8eef2',
};

/** URL of the illustration that best matches a product. */
export function productArt(name: string, subcategory: string | undefined, categorySlug: string): string {
  const n = ` ${name.toLowerCase()} `;
  const groups = CATEGORY_GROUPS[categorySlug] ?? (Object.keys(GROUPS) as Array<keyof typeof GROUPS>);
  const hit = groups.flatMap((g) => GROUPS[g]).find(([re]) => re.test(n));
  const art = hit?.[1] ?? (subcategory && BY_SUBCATEGORY[subcategory]) ?? BY_CATEGORY[categorySlug] ?? 'shopping_bags';
  return `/art/${art}.svg`;
}
