-- DEMO DATA ONLY. Safe catalogue examples; no customer, order, or payment records.
insert into public.categories(name,slug,description,sort_order) values
('Groceries','groceries','Fresh food and pantry staples',1),('Ladies Wear','ladies-wear','Fashion for every you',2),('Baby Care','baby-care','Daily care for little ones',3),('Stationery','stationery','School and office essentials',4),('Toys','toys','Play and learning',5),('Kitchen & Household','kitchen-household','Make home better',6),('Beauty & Skincare','beauty-skincare','Everyday personal care',7),('Cafe & Fast Food','cafe-fast-food','Quick bites and drinks',8),('Deals & Offers','deals-offers','Latest savings',9) on conflict(slug) do nothing;
insert into public.products(category_id,name,slug,sku,brand,description,price,sale_price,unit,featured,bestseller)
select id,'Daawat Basmati Rice','daawat-basmati-rice-5kg','SKU00123','Daawat','Premium long-grain aromatic basmati rice.',1499,1199,'5kg',true,true from public.categories where slug='groceries' on conflict(slug) do nothing;
insert into public.products(category_id,name,slug,sku,brand,description,price,sale_price,unit,featured,bestseller)
select id,'Maggi 2-Minute Noodles','maggi-2-minute-noodles','SKU00124','Maggi','Quick masala noodles.',190,160,'280g',true,true from public.categories where slug='groceries' on conflict(slug) do nothing;
insert into public.inventory(product_id,current_stock,reserved_stock,low_stock_threshold) select id,case when sku='SKU00123' then 8 else 120 end,0,10 from public.products where sku in('SKU00123','SKU00124') on conflict(product_id) do nothing;
insert into public.offers(name,offer_type,product_id,discount_type,discount_value,starts_at,ends_at,status,description) select 'Rice Special','PRODUCT',id,'PERCENTAGE',20,now(),now()+interval '30 days','ACTIVE','Demo offer' from public.products where sku='SKU00123';
insert into public.store_settings(store_name,address,phone,email,opening_time,closing_time,currency,timezone,delivery_radius_km,delivery_fee,min_order,estimated_delivery_minutes) values('Delight Shopping Mart','Ward No. 6, Tulsipur, Dang, Lumbini Province, Nepal','+977 9841234567','info@delightmart.com.np','07:00','21:00','NPR','Asia/Kathmandu',8,0,1000,20);
