import type { Product } from '@/types/store';
import rice from '@/assets/products/rice.jpg'; import noodles from '@/assets/products/noodles.jpg'; import lotion from '@/assets/products/lotion.jpg'; import tshirt from '@/assets/products/tshirt.jpg'; import diapers from '@/assets/products/diapers.jpg'; import notebook from '@/assets/products/notebook.jpg'; import headphones from '@/assets/products/headphones.jpg'; import shoes from '@/assets/products/shoes.jpg'; import watch from '@/assets/products/watch.jpg'; import backpack from '@/assets/products/backpack.jpg'; import oil from '@/assets/products/oil.jpg'; import bananas from '@/assets/products/bananas.jpg';
import groceries from '@/assets/categories/groceries.jpg'; import fashion from '@/assets/categories/fashion.jpg'; import baby from '@/assets/categories/baby.jpg'; import stationery from '@/assets/categories/stationery.jpg'; import toys from '@/assets/categories/toys.jpg'; import kitchen from '@/assets/categories/kitchen.jpg'; import beauty from '@/assets/categories/beauty.jpg'; import cafe from '@/assets/categories/cafe.jpg'; import offers from '@/assets/categories/offers.jpg';
export const categories=[
 {name:'Groceries',slug:'groceries',image:groceries},{name:'Ladies Wear',slug:'ladies-wear',image:fashion},{name:'Baby Care',slug:'baby-care',image:baby},{name:'Stationery',slug:'stationery',image:stationery},{name:'Toys',slug:'toys',image:toys},{name:'Kitchen & Household',slug:'kitchen-household',image:kitchen},{name:'Beauty & Skincare',slug:'beauty-skincare',image:beauty},{name:'Cafe & Fast Food',slug:'cafe-fast-food',image:cafe},{name:'Deals & Offers',slug:'deals-offers',image:offers},
];
export const products:Product[]=[
{id:'1',slug:'daawat-basmati-rice-5kg',name:'Daawat Basmati Rice',category:'Groceries',unit:'5kg',price:1199,oldPrice:1499,image:rice,discount:20,stock:8,rating:4.6,reviews:124,featured:true,description:'Premium long-grain aromatic basmati rice, ideal for everyday meals and special occasions.'},
{id:'2',slug:'maggi-2-minute-noodles',name:'Maggi 2-Minute Noodles',category:'Groceries',unit:'280g',price:160,oldPrice:190,image:noodles,discount:15,stock:120,rating:4.7,reviews:89,featured:true,description:'Quick, comforting noodles with a delicious masala flavour.'},
{id:'3',slug:'nivea-body-lotion-400ml',name:'Nivea Body Lotion',category:'Beauty & Skincare',unit:'400ml',price:425,oldPrice:475,image:lotion,discount:10,stock:45,rating:4.5,reviews:61,featured:true,description:'Daily moisturizing body lotion for smooth, nourished skin.'},
{id:'4',slug:'nike-ladies-t-shirt',name:'Nike Ladies T-Shirt',category:'Ladies Wear',unit:'1 pc',price:799,oldPrice:1050,image:tshirt,discount:25,stock:32,rating:4.4,reviews:42,featured:true,description:'Comfortable everyday cotton t-shirt with a modern fit.'},
{id:'5',slug:'pampers-baby-diapers',name:'Pampers Baby Diapers',category:'Baby Care',unit:'Large pack',price:1350,oldPrice:1590,image:diapers,discount:15,stock:24,rating:4.8,reviews:107,description:'Soft and absorbent baby diapers for lasting comfort.'},
{id:'6',slug:'classmate-notebook',name:'Classmate Notebook',category:'Stationery',unit:'1 pc',price:60,oldPrice:70,image:notebook,discount:10,stock:200,rating:4.5,reviews:32,description:'Quality single-line notebook for school and office.'},
{id:'7',slug:'wireless-headphones',name:'Wireless Headphones',category:'Electronics',unit:'1 pc',price:2999,oldPrice:4999,image:headphones,discount:40,stock:18,rating:4.6,reviews:78,featured:true,description:'Immersive wireless sound with a comfortable over-ear fit.'},
{id:'8',slug:'running-shoes',name:'Running Shoes',category:'Fashion',unit:'1 pair',price:1899,oldPrice:2999,image:shoes,discount:37,stock:26,rating:4.5,reviews:55,description:'Lightweight sports shoes for daily runs and walks.'},
{id:'9',slug:'smart-watch',name:'Smart Watch',category:'Electronics',unit:'1 pc',price:3499,oldPrice:5999,image:watch,discount:42,stock:15,rating:4.4,reviews:91,description:'Fitness tracking, alerts and everyday smart features.'},
{id:'10',slug:'travel-backpack',name:'Travel Backpack',category:'Fashion',unit:'1 pc',price:1299,oldPrice:2499,image:backpack,discount:48,stock:38,rating:4.7,reviews:48,description:'Spacious, durable backpack for work and travel.'},
{id:'11',slug:'sunflower-oil-1l',name:'Sunflower Oil',category:'Groceries',unit:'1L',price:210,oldPrice:260,image:oil,discount:19,stock:50,rating:4.6,reviews:38,isNew:true,description:'Light, refined sunflower oil for everyday cooking.'},
{id:'12',slug:'fresh-banana-1kg',name:'Fresh Banana',category:'Groceries',unit:'1kg',price:120,image:bananas,stock:60,rating:4.8,reviews:28,isNew:true,description:'Fresh, naturally sweet bananas selected daily.'},
];
export const getProduct=(slug:string)=>products.find(p=>p.slug===slug);
export const formatNpr=(n:number)=>`NPR ${n.toLocaleString('en-US')}`;
