export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  subcategory?: string | undefined;
  brand?: string | undefined;
  unit: string;
  price: number;
  oldPrice?: number | undefined;
  image: string;
  gallery?: string[] | undefined;
  discount?: number | undefined;
  stock: number;
  rating: number;
  reviews: number;
  featured?: boolean | undefined;
  isNew?: boolean | undefined;
  description: string;
};
export type CartLine = { product: Product; quantity: number };
export type OrderStatus = 'Pending' | 'Preparing' | 'Out for Delivery' | 'Delivered' | 'Cancelled';
