/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReviewOrderRouteImport } from './routes/review-order'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoreLocationRouteImport } from './routes/store-location'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountHelpRouteImport } from './routes/account/help'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountOffersRouteImport } from './routes/account/offers'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountPaymentsRouteImport } from './routes/account/payments'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewOrderRoute = ReviewOrderRouteImport.update({
  id: '/review-order',
  path: '/review-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocationRoute = StoreLocationRouteImport.update({
  id: '/store-location',
  path: '/store-location',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHelpRoute = AccountHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOffersRoute = AccountOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/review-order': typeof ReviewOrderRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/store-location': typeof StoreLocationRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/help': typeof AccountHelpRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/offers': typeof AccountOffersRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/review-order': typeof ReviewOrderRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/store-location': typeof StoreLocationRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/help': typeof AccountHelpRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/offers': typeof AccountOffersRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/review-order': typeof ReviewOrderRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/store-location': typeof StoreLocationRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/help': typeof AccountHelpRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/offers': typeof AccountOffersRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/app'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/payment'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/review-order'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/store-location'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/wishlist'
    | '/account/addresses'
    | '/account/help'
    | '/account/notifications'
    | '/account/offers'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/security'
    | '/account/settings'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/inventory'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
    | '/categories/$slug'
    | '/orders/$id'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/categories/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/payment'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/review-order'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/store-location'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/wishlist'
    | '/account/addresses'
    | '/account/help'
    | '/account/notifications'
    | '/account/offers'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/security'
    | '/account/settings'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/inventory'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
    | '/categories/$slug'
    | '/orders/$id'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/categories'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/app'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/payment'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/review-order'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/store-location'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/wishlist'
    | '/account/addresses'
    | '/account/help'
    | '/account/notifications'
    | '/account/offers'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/security'
    | '/account/settings'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/inventory'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
    | '/categories/$slug'
    | '/orders/$id'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/categories/'
    | '/orders/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  ReviewOrderRoute: typeof ReviewOrderRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  SignupRoute: typeof SignupRoute
  StoreLocationRoute: typeof StoreLocationRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  WishlistRoute: typeof WishlistRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-order': {
      id: '/review-order'
      path: '/review-order'
      fullPath: '/review-order'
      preLoaderRoute: typeof ReviewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-location': {
      id: '/store-location'
      path: '/store-location'
      fullPath: '/store-location'
      preLoaderRoute: typeof StoreLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/help': {
      id: '/account/help'
      path: '/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof AccountHelpRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/offers': {
      id: '/account/offers'
      path: '/offers'
      fullPath: '/account/offers'
      preLoaderRoute: typeof AccountOffersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountHelpRoute: typeof AccountHelpRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOffersRoute: typeof AccountOffersRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountHelpRoute: AccountHelpRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOffersRoute: AccountOffersRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  ReviewOrderRoute: ReviewOrderRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  SignupRoute: SignupRoute,
  StoreLocationRoute: StoreLocationRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  WishlistRoute: WishlistRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
