insert into public.categories(name,slug,description,sort_order) values ('Groceries','groceries','Fresh food and pantry staples',1),('Ladies Wear','ladies-wear','Fashion for every you',2),('Baby Care','baby-care','Daily care for little ones',3),('Stationery','stationery','School and office essentials',4),('Toys','toys','Play and learning',5),('Kitchen & Household','kitchen-household','Make home better',6),('Beauty & Skincare','beauty-skincare','Everyday personal care',7),('Cafe & Fast Food','cafe-fast-food','Quick bites and drinks',8),('Deals & Offers','deals-offers','Latest savings',9) on conflict(slug) do nothing;
with source(slug,name,sku,category_slug,price,unit,description,featured) as (values
('daawat-basmati-rice-5kg','Daawat Basmati Rice','SKU00123','groceries',1199::numeric,'5kg','Premium long-grain aromatic basmati rice, ideal for everyday meals and special occasions.',true),
('maggi-2-minute-noodles','Maggi 2-Minute Noodles','SKU00124','groceries',160::numeric,'280g','Quick, comforting noodles with a delicious masala flavour.',true),
('nivea-body-lotion-400ml','Nivea Body Lotion','SKU00125','beauty-skincare',425::numeric,'400ml','Daily moisturizing body lotion.',true),
('nike-ladies-t-shirt','Nike Ladies T-Shirt','SKU00126','ladies-wear',799::numeric,'1 pc','Comfortable everyday cotton t-shirt.',true),
('pampers-baby-diapers','Pampers Baby Diapers','SKU00127','baby-care',1350::numeric,'Large pack','Soft and absorbent baby diapers.',false),
('classmate-notebook','Classmate Notebook','SKU00128','stationery',60::numeric,'1 pc','Quality notebook for school and office.',false),
('wireless-headphones','Wireless Headphones','SKU00129','kitchen-household',2999::numeric,'1 pc','Immersive wireless sound.',true),
('running-shoes','Running Shoes','SKU00130','ladies-wear',1899::numeric,'1 pair','Lightweight sports shoes.',false),
('smart-watch','Smart Watch','SKU00131','kitchen-household',3499::numeric,'1 pc','Fitness tracking and alerts.',false),
('travel-backpack','Travel Backpack','SKU00132','ladies-wear',1299::numeric,'1 pc','Spacious, durable backpack.',false),
('sunflower-oil-1l','Sunflower Oil','SKU00133','groceries',210::numeric,'1L','Refined sunflower oil for everyday cooking.',false),
('fresh-banana-1kg','Fresh Banana','SKU00134','groceries',120::numeric,'1kg','Fresh, naturally sweet bananas.',false))
insert into public.products(category_id,name,slug,sku,description,price,unit,featured) select c.id,s.name,s.slug,s.sku,s.description,s.price,s.unit,s.featured from source s join public.categories c on c.slug=s.category_slug on conflict(slug) do nothing;
insert into public.inventory(product_id,current_stock,reserved_stock,low_stock_threshold) select p.id,case p.slug when 'daawat-basmati-rice-5kg' then 8 when 'maggi-2-minute-noodles' then 120 when 'nivea-body-lotion-400ml' then 45 when 'nike-ladies-t-shirt' then 32 when 'pampers-baby-diapers' then 24 when 'classmate-notebook' then 200 when 'wireless-headphones' then 18 when 'running-shoes' then 26 when 'smart-watch' then 15 when 'travel-backpack' then 38 when 'sunflower-oil-1l' then 50 else 60 end,0,10 from public.products p where p.slug in ('daawat-basmati-rice-5kg','maggi-2-minute-noodles','nivea-body-lotion-400ml','nike-ladies-t-shirt','pampers-baby-diapers','classmate-notebook','wireless-headphones','running-shoes','smart-watch','travel-backpack','sunflower-oil-1l','fresh-banana-1kg') on conflict(product_id) do nothing;
insert into public.store_settings(store_name,address,phone,email,opening_time,closing_time,currency,timezone,delivery_radius_km,delivery_fee,min_order,estimated_delivery_minutes) select 'Delight Shopping Mart','Ward No. 6, Tulsipur, Dang, Lumbini Province, Nepal',null,null,'07:00','21:00','NPR','Asia/Kathmandu',8,0,0,20 where not exists(select 1 from public.store_settings);