-- Delight Shopping Mart production schema
create extension if not exists pgcrypto;
create type public.app_role as enum ('SUPER_ADMIN','MANAGER','ORDER_STAFF','INVENTORY_STAFF','DELIVERY_STAFF','CUSTOMER');
create type public.product_status as enum ('ACTIVE','INACTIVE','DRAFT');
create type public.order_status as enum ('PENDING','CONFIRMED','PREPARING','READY_FOR_DELIVERY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','FAILED');
create type public.payment_status as enum ('PENDING','PAID','FAILED','REFUNDED','PARTIAL_REFUND');
create type public.delivery_status as enum ('PENDING','READY','OUT_FOR_DELIVERY','DELIVERED','FAILED');

create table public.profiles(id uuid primary key,full_name text not null,email text,phone text,avatar_url text,status text not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
grant select,insert,update on public.profiles to authenticated; grant all on public.profiles to service_role; alter table public.profiles enable row level security;
create table public.user_roles(id uuid primary key default gen_random_uuid(),user_id uuid not null,role public.app_role not null default 'CUSTOMER',unique(user_id,role));
grant select on public.user_roles to authenticated; grant all on public.user_roles to service_role; alter table public.user_roles enable row level security;
create or replace function public.has_role(_user_id uuid,_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.user_roles where user_id=_user_id and role=_role)$$;
grant execute on function public.has_role(uuid,public.app_role) to authenticated;
create or replace function public.is_staff(_user_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.user_roles where user_id=_user_id and role in ('SUPER_ADMIN','MANAGER','ORDER_STAFF','INVENTORY_STAFF','DELIVERY_STAFF'))$$;
grant execute on function public.is_staff(uuid) to authenticated;
create policy "profiles own read" on public.profiles for select to authenticated using(id=auth.uid() or public.is_staff(auth.uid())); create policy "profiles own update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid()); create policy "profiles own insert" on public.profiles for insert to authenticated with check(id=auth.uid());
create policy "roles own read" on public.user_roles for select to authenticated using(user_id=auth.uid() or public.has_role(auth.uid(),'SUPER_ADMIN'));

create table public.categories(id uuid primary key default gen_random_uuid(),parent_id uuid references public.categories(id) on delete set null,name text not null,slug text not null unique,description text,image_url text,status public.product_status not null default 'ACTIVE',sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
grant select on public.categories to anon,authenticated; grant insert,update,delete on public.categories to authenticated; grant all on public.categories to service_role; alter table public.categories enable row level security;
create policy "active categories public" on public.categories for select to anon,authenticated using(status='ACTIVE' or public.is_staff(auth.uid())); create policy "staff categories write" on public.categories for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.products(id uuid primary key default gen_random_uuid(),category_id uuid not null references public.categories(id),name text not null,slug text not null unique,sku text not null unique,brand text,description text not null default '',price numeric(12,2) not null check(price>=0),sale_price numeric(12,2) check(sale_price>=0),unit text not null default '1 pc',status public.product_status not null default 'ACTIVE',featured boolean not null default false,bestseller boolean not null default false,specifications jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
grant select on public.products to anon,authenticated; grant insert,update,delete on public.products to authenticated; grant all on public.products to service_role; alter table public.products enable row level security;
create policy "active products public" on public.products for select to anon,authenticated using(status='ACTIVE' or public.is_staff(auth.uid())); create policy "staff products write" on public.products for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,url text not null,alt_text text,sort_order int not null default 0,is_primary boolean not null default false);
grant select on public.product_images to anon,authenticated; grant insert,update,delete on public.product_images to authenticated; grant all on public.product_images to service_role; alter table public.product_images enable row level security;
create policy "product images public" on public.product_images for select to anon,authenticated using(exists(select 1 from public.products p where p.id=product_id and p.status='ACTIVE') or public.is_staff(auth.uid())); create policy "staff product images write" on public.product_images for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.inventory(product_id uuid primary key references public.products(id) on delete cascade,current_stock int not null default 0 check(current_stock>=0),reserved_stock int not null default 0 check(reserved_stock>=0 and reserved_stock<=current_stock),low_stock_threshold int not null default 10,last_updated timestamptz not null default now());
grant select on public.inventory to anon,authenticated; grant insert,update,delete on public.inventory to authenticated; grant all on public.inventory to service_role; alter table public.inventory enable row level security;
create policy "inventory availability public" on public.inventory for select to anon,authenticated using(true); create policy "inventory staff write" on public.inventory for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.inventory_adjustments(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id),changed_by uuid,quantity_delta int not null,reason text not null,reference text,created_at timestamptz not null default now());
grant select,insert on public.inventory_adjustments to authenticated; grant all on public.inventory_adjustments to service_role; alter table public.inventory_adjustments enable row level security; create policy "inventory staff adjustments" on public.inventory_adjustments for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));

create table public.addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null,label text not null,recipient_name text not null,phone text not null,address_line text not null,city text not null default 'Tulsipur',province text not null default 'Lumbini Province',latitude numeric,longitude numeric,is_default boolean not null default false,created_at timestamptz not null default now());
grant select,insert,update,delete on public.addresses to authenticated; grant all on public.addresses to service_role; alter table public.addresses enable row level security; create policy "addresses own" on public.addresses for all to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid())) with check(user_id=auth.uid() or public.is_staff(auth.uid()));
create table public.cart(id uuid primary key default gen_random_uuid(),user_id uuid not null unique,updated_at timestamptz not null default now());
grant select,insert,update,delete on public.cart to authenticated; grant all on public.cart to service_role; alter table public.cart enable row level security; create policy "cart own" on public.cart for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create table public.cart_items(id uuid primary key default gen_random_uuid(),cart_id uuid not null references public.cart(id) on delete cascade,product_id uuid not null references public.products(id),quantity int not null check(quantity>0),unique(cart_id,product_id));
grant select,insert,update,delete on public.cart_items to authenticated; grant all on public.cart_items to service_role; alter table public.cart_items enable row level security; create policy "cart items own" on public.cart_items for all to authenticated using(exists(select 1 from public.cart c where c.id=cart_id and c.user_id=auth.uid())) with check(exists(select 1 from public.cart c where c.id=cart_id and c.user_id=auth.uid()));

create table public.orders(id uuid primary key default gen_random_uuid(),order_number text not null unique,user_id uuid not null,address_id uuid references public.addresses(id),status public.order_status not null default 'PENDING',subtotal numeric(12,2) not null,discount numeric(12,2) not null default 0,delivery_fee numeric(12,2) not null default 0,platform_fee numeric(12,2) not null default 0,total numeric(12,2) not null,payment_method text not null,delivery_instructions text,estimated_delivery_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
grant select,insert,update on public.orders to authenticated; grant all on public.orders to service_role; alter table public.orders enable row level security; create policy "orders own or staff read" on public.orders for select to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid())); create policy "orders own insert" on public.orders for insert to authenticated with check(user_id=auth.uid()); create policy "staff update orders" on public.orders for update to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id),product_name text not null,sku text,quantity int not null check(quantity>0),unit_price numeric(12,2) not null,line_total numeric(12,2) not null);
grant select,insert on public.order_items to authenticated; grant all on public.order_items to service_role; alter table public.order_items enable row level security; create policy "order items own or staff" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_staff(auth.uid())))); create policy "order items customer insert" on public.order_items for insert to authenticated with check(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create table public.delivery_assignments(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders(id) on delete cascade,staff_id uuid,status public.delivery_status not null default 'PENDING',assigned_at timestamptz,delivered_at timestamptz,failure_reason text,notes text,updated_at timestamptz not null default now());
grant select,insert,update on public.delivery_assignments to authenticated; grant all on public.delivery_assignments to service_role; alter table public.delivery_assignments enable row level security; create policy "delivery visible to owner staff" on public.delivery_assignments for select to authenticated using(staff_id=auth.uid() or public.is_staff(auth.uid()) or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid())); create policy "delivery staff write" on public.delivery_assignments for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.payments(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id),provider text not null,provider_transaction_id text,status public.payment_status not null default 'PENDING',amount numeric(12,2) not null,currency text not null default 'NPR',verified_at timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now());
grant select on public.payments to authenticated; grant all on public.payments to service_role; alter table public.payments enable row level security; create policy "payments own or staff" on public.payments for select to authenticated using(public.is_staff(auth.uid()) or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));

create table public.coupons(id uuid primary key default gen_random_uuid(),code text not null unique,discount_type text not null check(discount_type in('PERCENTAGE','FIXED')),discount_value numeric not null,min_order numeric not null default 0,usage_limit int,used_count int not null default 0,starts_at timestamptz,ends_at timestamptz,status text not null default 'ACTIVE',created_at timestamptz not null default now());
grant select on public.coupons to authenticated; grant insert,update,delete on public.coupons to authenticated; grant all on public.coupons to service_role; alter table public.coupons enable row level security; create policy "active coupons authenticated" on public.coupons for select to authenticated using(status='ACTIVE' or public.is_staff(auth.uid())); create policy "staff coupons write" on public.coupons for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.offers(id uuid primary key default gen_random_uuid(),name text not null,offer_type text not null check(offer_type in('PRODUCT','CATEGORY','COUPON','SHIPPING')),product_id uuid references public.products(id),category_id uuid references public.categories(id),discount_type text not null,discount_value numeric not null,starts_at timestamptz,ends_at timestamptz,usage_limit int,status text not null default 'ACTIVE',description text,created_at timestamptz not null default now());
grant select on public.offers to anon,authenticated; grant insert,update,delete on public.offers to authenticated; grant all on public.offers to service_role; alter table public.offers enable row level security; create policy "active offers public" on public.offers for select to anon,authenticated using(status='ACTIVE' or public.is_staff(auth.uid())); create policy "staff offers write" on public.offers for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.banners(id uuid primary key default gen_random_uuid(),title text not null,image_url text not null,link_url text,position text not null,status text not null default 'ACTIVE',starts_at timestamptz,ends_at timestamptz,sort_order int not null default 0,created_at timestamptz not null default now());
grant select on public.banners to anon,authenticated; grant insert,update,delete on public.banners to authenticated; grant all on public.banners to service_role; alter table public.banners enable row level security; create policy "active banners public" on public.banners for select to anon,authenticated using(status='ACTIVE' or public.is_staff(auth.uid())); create policy "staff banners write" on public.banners for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
create table public.reviews(id uuid primary key default gen_random_uuid(),user_id uuid not null,product_id uuid not null references public.products(id),order_id uuid references public.orders(id),rating int not null check(rating between 1 and 5),review text not null,status text not null default 'PENDING',created_at timestamptz not null default now(),unique(user_id,product_id,order_id));
grant select on public.reviews to anon,authenticated; grant insert,update,delete on public.reviews to authenticated; grant all on public.reviews to service_role; alter table public.reviews enable row level security; create policy "published reviews public" on public.reviews for select to anon,authenticated using(status='PUBLISHED' or user_id=auth.uid() or public.is_staff(auth.uid())); create policy "reviews own insert" on public.reviews for insert to authenticated with check(user_id=auth.uid()); create policy "reviews own update" on public.reviews for update to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid())) with check(user_id=auth.uid() or public.is_staff(auth.uid()));
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null,title text not null,body text not null,type text not null,read_at timestamptz,created_at timestamptz not null default now());
grant select,update,delete on public.notifications to authenticated; grant all on public.notifications to service_role; alter table public.notifications enable row level security; create policy "notifications own" on public.notifications for select to authenticated using(user_id=auth.uid()); create policy "notifications own update" on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create table public.store_settings(id uuid primary key default gen_random_uuid(),store_name text not null,address text not null,phone text,email text,logo_url text,opening_time time,closing_time time,currency text not null default 'NPR',timezone text not null default 'Asia/Kathmandu',delivery_radius_km numeric,delivery_fee numeric,min_order numeric,estimated_delivery_minutes int,delivery_available boolean not null default true,updated_at timestamptz not null default now());
grant select on public.store_settings to anon,authenticated; grant insert,update on public.store_settings to authenticated; grant all on public.store_settings to service_role; alter table public.store_settings enable row level security; create policy "store settings public" on public.store_settings for select to anon,authenticated using(true); create policy "admins settings write" on public.store_settings for all to authenticated using(public.has_role(auth.uid(),'SUPER_ADMIN') or public.has_role(auth.uid(),'MANAGER')) with check(public.has_role(auth.uid(),'SUPER_ADMIN') or public.has_role(auth.uid(),'MANAGER'));

create index products_category_status_idx on public.products(category_id,status);create index orders_user_created_idx on public.orders(user_id,created_at desc);create index orders_status_created_idx on public.orders(status,created_at desc);create index delivery_staff_status_idx on public.delivery_assignments(staff_id,status);create index reviews_product_status_idx on public.reviews(product_id,status);create index notifications_user_created_idx on public.notifications(user_id,created_at desc);
create policy "public storefront media" on storage.objects for select to public using(bucket_id in('product-images','category-images','banners','store-branding'));create policy "staff storefront uploads" on storage.objects for all to authenticated using(bucket_id in('product-images','category-images','banners','store-branding') and public.is_staff(auth.uid())) with check(bucket_id in('product-images','category-images','banners','store-branding') and public.is_staff(auth.uid()));create policy "profile images own" on storage.objects for all to authenticated using(bucket_id='profile-images' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='profile-images' and (storage.foldername(name))[1]=auth.uid()::text);
