create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;
alter function public.has_role(uuid, public.app_role) set schema private;
alter function public.is_staff(uuid) set schema private;
revoke all on function private.has_role(uuid, public.app_role) from public, anon;
revoke all on function private.is_staff(uuid) from public, anon;
grant execute on function private.has_role(uuid, public.app_role) to authenticated, service_role;
grant execute on function private.is_staff(uuid) to authenticated, service_role;

alter policy "profiles own read" on public.profiles using(id=auth.uid() or private.is_staff(auth.uid()));
alter policy "roles own read" on public.user_roles using(user_id=auth.uid() or private.has_role(auth.uid(),'SUPER_ADMIN'));
alter policy "active categories public" on public.categories using(status='ACTIVE' or private.is_staff(auth.uid()));
alter policy "staff categories write" on public.categories using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "active products public" on public.products using(status='ACTIVE' or private.is_staff(auth.uid()));
alter policy "staff products write" on public.products using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "product images public" on public.product_images using(exists(select 1 from public.products p where p.id=product_id and p.status='ACTIVE') or private.is_staff(auth.uid()));
alter policy "staff product images write" on public.product_images using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "inventory staff write" on public.inventory using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "inventory staff adjustments" on public.inventory_adjustments using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "addresses own" on public.addresses using(user_id=auth.uid() or private.is_staff(auth.uid())) with check(user_id=auth.uid() or private.is_staff(auth.uid()));
alter policy "orders own or staff read" on public.orders using(user_id=auth.uid() or private.is_staff(auth.uid()));
alter policy "staff update orders" on public.orders using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "order items own or staff" on public.order_items using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or private.is_staff(auth.uid()))));
alter policy "delivery visible to owner staff" on public.delivery_assignments using(staff_id=auth.uid() or private.is_staff(auth.uid()) or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
alter policy "delivery staff write" on public.delivery_assignments using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "payments own or staff" on public.payments using(private.is_staff(auth.uid()) or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
alter policy "active coupons authenticated" on public.coupons using(status='ACTIVE' or private.is_staff(auth.uid()));
alter policy "staff coupons write" on public.coupons using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "active offers public" on public.offers using(status='ACTIVE' or private.is_staff(auth.uid()));
alter policy "staff offers write" on public.offers using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "active banners public" on public.banners using(status='ACTIVE' or private.is_staff(auth.uid()));
alter policy "staff banners write" on public.banners using(private.is_staff(auth.uid())) with check(private.is_staff(auth.uid()));
alter policy "published reviews public" on public.reviews using(status='PUBLISHED' or user_id=auth.uid() or private.is_staff(auth.uid()));
alter policy "reviews own update" on public.reviews using(user_id=auth.uid() or private.is_staff(auth.uid())) with check(user_id=auth.uid() or private.is_staff(auth.uid()));
alter policy "admins settings write" on public.store_settings using(private.has_role(auth.uid(),'SUPER_ADMIN') or private.has_role(auth.uid(),'MANAGER')) with check(private.has_role(auth.uid(),'SUPER_ADMIN') or private.has_role(auth.uid(),'MANAGER'));

drop policy "staff storefront uploads" on storage.objects;
create policy "staff storefront uploads" on storage.objects for all to authenticated using(bucket_id in('product-images','category-images','banners','store-branding') and private.is_staff(auth.uid())) with check(bucket_id in('product-images','category-images','banners','store-branding') and private.is_staff(auth.uid()));